version: '3.9'

services:
  meu-coelhinho:
    image: rabbitmq:3.9-management

    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - /docker_conf/rabbitmq/data/:/var/lib/rabbitmq/
      - /docker_conf/rabbitmq/log/:/var/log/rabbitmq
    restart: always

volumes:
  logs-folder:
   name: ${log_rabbitmq_management}
   driver: local 